myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.homepage),
    path('about/',views.about),
    path('posts/', include('posts.urls'))#look inside posts-app in the urls-file
]

myproject/posts/urls.py
from django.urls import path
from .import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"), # we are already in the posts path so -> ''
    path('<slug:slug>', views.post_page, name="page") # we are already in the posts path so -> ''
    #it knows to look in our new templates directory in posts, for the posts_lists template 
]

myproject/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title

myproject/myproject/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

myproject/posts/views.py
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse

# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date') #gets all the post-objeacts
    return render(request, 'posts/posts_list.html', {'posts': posts}) #Ort des templates, es weiß wo der allg. Template Ordner ist, wegen settings.py
#1.bring post-model
#2.get all the posts
#3 pass the data on the template, so we can use it in our post-list template
# third param. in render()
#für 'posts' wird das query-set posts gespeichert

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

myproject/posts/templates/posts/post_page.html
{% extends 'layout.html' %} {% block title %}
  {{ post.title }}
{% endblock %} {% block content %}
  <section>
    <h1>{{ post.title }}</h1>

    <p>{{ post.date }}</p>
    <p>{{ post.body }}</p>
  </section>
{% endblock %}

myproject/posts/templates/posts/posts_list.html
{% extends 'layout.html' %} {% block title %}
  Posts
{% endblock %} {% block content %}
  <section>
    <h1>Posts</h1>

    {% for post in posts %}
      <article class="post">
        <h2><a href="{% url 'posts:page' slug=post.slug %}">{{ post.title }}</a></h2>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
      </article>
    {% endfor %}
  </section>
{% endblock %}

myproject/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>About</title>
    <script src="{% static 'js/main.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page</p>
  </body>
</html>

myproject/templates/home.html
{% extends 'layout.html' %} {% block title %}
  Home
{% endblock %} {% block content %}
  <h1>Home</h1>
  <p>
    Check out my <a href="/about">About</a> page
  </p>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Django App
      {% endblock %}
    </title>
    <script src="{% static 'js/main.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <nav>
      <a href="/">🏠</a> | <a href="/about">😃</a> | <a href="{% url 'posts:list' %}">📰</a> |
    </nav>
    <main>
      {% block content %}

      {% endblock %}
    </main>
  </body>
</html>